/**
 * Auto-generated by generate-media-list.js — do not edit by hand.
 * Add files to the media/ folder, then run: node generate-media-list.js
 */

window.mediaData = [
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.14.08 AM (1).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.14.08 AM (2).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.14.08 AM (3).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.14.08 AM (4).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.14.08 AM (5).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.14.08 AM.jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.26 AM (1).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.26 AM (2).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.26 AM (3).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.26 AM (4).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.26 AM (5).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.26 AM (6).jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.26 AM.jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Image 2026-02-13 at 12.15.35 AM.jpeg",
    "type": "image"
  },
  {
    "url": "media/WhatsApp Video 2026-02-13 at 12.14.09 AM.mp4",
    "type": "video"
  }
];
