/**
 * Auto-generated by generate-media-list.js — do not edit by hand.
 * Add files to the media/ folder, then run: node generate-media-list.js
 */

window.mediaData = [
  {
    "url": "media/0 (1).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (1).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (10).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (11).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (12).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (13).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (14).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (15).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (16).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (17).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (18).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (19).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (2).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (2).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (20).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (3).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (3).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (4).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (4).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (5).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (5).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (6).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (6).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (7).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (7).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (8).jpeg",
    "type": "image"
  },
  {
    "url": "media/0 (8).mp4",
    "type": "video"
  },
  {
    "url": "media/0 (9).jpeg",
    "type": "image"
  }
];
